import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

type DocumentItem = {
  ItemDesc: string;
  Qty: number;
  UnitExcl: number;
  UnitIncl: number;
  VatAmount: number;
  Amount: number;
};

type DocumentData = {
  number: string;
  company: string;
  date: string;
  storeName?: string;
  storeCode?: string;
  tel?: string;
  email?: string;
  subtotal: number;
  vatTotal: number;
  total: number;
  paymentMethod?: string;
  items: DocumentItem[];
};

const money = (value: number) => `R ${Number(value || 0).toFixed(2)}`;

const escapeHtml = (value: string) =>
  String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export async function generateDocumentPdf(
  type: 'INVOICE' | 'QUOTE',
  data: DocumentData
): Promise<string> {
  const title = type === 'INVOICE' ? 'TAX INVOICE' : 'QUOTATION';
  const rows = data.items.map(item => `
    <tr>
      <td>${escapeHtml(item.ItemDesc)}</td>
      <td class="right">${item.Qty}</td>
      <td class="right">${money(item.UnitExcl)}</td>
      <td class="right">${money(item.VatAmount)}</td>
      <td class="right">${money(item.Amount)}</td>
    </tr>
  `).join('');

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          body { font-family: Arial, sans-serif; color: #111827; padding: 32px; }
          .top { display: flex; justify-content: space-between; margin-bottom: 28px; }
          h1 { margin: 0 0 6px; font-size: 24px; }
          .muted { color: #6b7280; font-size: 12px; }
          .number { font-size: 18px; font-weight: bold; }
          .box { background: #f3f4f6; padding: 14px; margin-bottom: 22px; }
          table { width: 100%; border-collapse: collapse; margin-top: 18px; }
          th { background: #111827; color: white; text-align: left; padding: 9px; font-size: 11px; }
          td { border-bottom: 1px solid #e5e7eb; padding: 9px; font-size: 11px; }
          .right { text-align: right; }
          .totals { width: 280px; margin-left: auto; margin-top: 22px; }
          .totalRow { display: flex; justify-content: space-between; padding: 5px 0; }
          .grand { border-top: 2px solid #111827; font-size: 16px; font-weight: bold; padding-top: 9px; }
          .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; font-size: 10px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="top">
          <div>
            <h1>${escapeHtml(data.storeName || 'Mobile POS')}</h1>
            <div class="muted">${escapeHtml(data.storeCode || '')}</div>
            <div class="muted">${escapeHtml(data.tel || '')}</div>
            <div class="muted">${escapeHtml(data.email || '')}</div>
          </div>
          <div style="text-align:right">
            <div class="number">${title}</div>
            <div class="muted">${escapeHtml(data.number)}</div>
            <div class="muted">${escapeHtml(data.date)}</div>
          </div>
        </div>

        <div class="box">
          <strong>Customer</strong><br />
          ${escapeHtml(data.company)}
        </div>

        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th class="right">Qty</th>
              <th class="right">Unit Excl.</th>
              <th class="right">VAT</th>
              <th class="right">Total</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>

        <div class="totals">
          <div class="totalRow"><span>Subtotal (excl. VAT)</span><strong>${money(data.subtotal)}</strong></div>
          <div class="totalRow"><span>VAT</span><strong>${money(data.vatTotal)}</strong></div>
          <div class="totalRow grand"><span>Total</span><strong>${money(data.total)}</strong></div>
          ${data.paymentMethod ? `<div class="totalRow"><span>Payment</span><strong>${escapeHtml(data.paymentMethod)}</strong></div>` : ''}
        </div>

        <div class="footer">
          Generated by Mobile POS. This document is stored locally on the device.
        </div>
      </body>
    </html>
  `;

  const result = await Print.printToFileAsync({
    html,
    base64: true,
  });

  if (!result.base64) {
    throw new Error(
      result.uri
        ? 'PDF was generated but Android did not return readable PDF data.'
        : 'PDF generation did not return any PDF data.'
    );
  }

  const safeName = data.number.replace(/[^a-zA-Z0-9_-]/g, '_');
  const targetUri = `${FileSystem.documentDirectory}${safeName}.pdf`;

  await FileSystem.writeAsStringAsync(targetUri, result.base64, {
    encoding: FileSystem.EncodingType.Base64,
  });

  const savedInfo = await FileSystem.getInfoAsync(targetUri);
  if (!savedInfo.exists) {
    throw new Error('PDF was generated but could not be saved to local storage.');
  }

  return targetUri;
}

export async function shareDocumentPdf(uri: string) {
  const available = await Sharing.isAvailableAsync();
  if (!available) throw new Error('Sharing is not available on this device.');

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Share PDF',
    UTI: 'com.adobe.pdf',
  });
}
