import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

type DocumentItem = {
  ItemDesc: string;
  Qty: number;
  UnitExcl: number;
  UnitIncl: number;
  VatAmount: number;
  Amount: number;
  Discount?: number;
};

type DocumentData = {
  number: string;
  company: string;
  date: string;
  storeName?: string;
  storeCode?: string;
  tel?: string;
  email?: string;
  subtotal: number;
  vatTotal: number;
  total: number;
  paymentMethod?: string;
  items: DocumentItem[];
};

const money = (value: number) => `R ${Number(value || 0).toFixed(2)}`;

const escapeHtml = (value: string) =>
  String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export async function generateDocumentPdf(
  type: 'INVOICE' | 'QUOTE',
  data: DocumentData
): Promise<string> {
  const title = type === 'INVOICE' ? 'TAX INVOICE' : 'QUOTATION';
  const rows = data.items.map(item => `
    <tr>
      <td>${escapeHtml(item.ItemDesc)}</td>
      <td class="right">${item.Qty}</td>
      <td class="right">${money(item.UnitExcl)}</td>
      <td class="right">${money(item.VatAmount)}</td>
      <td class="right">${money(item.Discount || 0)}</td>
      <td class="right">${money(item.Amount)}</td>
    </tr>
  `).join('');

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          body { font-family: Arial, sans-serif; color: #111827; padding: 32px; }
          .top { display: flex; justify-content: space-between; margin-bottom: 28px; }
          h1 { margin: 0 0 6px; font-size: 24px; }
          .muted { color: #6b7280; font-size: 12px; }
          .number { font-size: 18px; font-weight: bold; }
          .box { background: #f3f4f6; padding: 14px; margin-bottom: 22px; }
          table { width: 100%; border-collapse: collapse; margin-top: 18px; }
          th { background: #111827; color: white; text-align: left; padding: 9px; font-size: 11px; }
          td { border-bottom: 1px solid #e5e7eb; padding: 9px; font-size: 11px; }
          .right { text-align: right; }
          .totals { width: 280px; margin-left: auto; margin-top: 22px; }
          .totalRow { display: flex; justify-content: space-between; padding: 5px 0; }
          .grand { border-top: 2px solid #111827; font-size: 16px; font-weight: bold; padding-top: 9px; }
          .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; font-size: 10px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="top">
          <div>
            <h1>${escapeHtml(data.storeName || 'Mobile POS')}</h1>
            <div class="muted">${escapeHtml(data.storeCode || '')}</div>
            <div class="muted">${escapeHtml(data.tel || '')}</div>
            <div class="muted">${escapeHtml(data.email || '')}</div>
          </div>
          <div style="text-align:right">
            <div class="number">${title}</div>
            <div class="muted">${escapeHtml(data.number)}</div>
            <div class="muted">${escapeHtml(data.date)}</div>
          </div>
        </div>

        <div class="box">
          <strong>Customer</strong><br />
          ${escapeHtml(data.company)}
        </div>

        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th class="right">Qty</th>
              <th class="right">Unit Excl.</th>
              <th class="right">VAT</th>
              <th class="right">Discount</th>
              <th class="right">Total</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>

        <div class="totals">
          <div class="totalRow"><span>Subtotal (excl. VAT)</span><strong>${money(data.subtotal)}</strong></div>
          <div class="totalRow"><span>VAT</span><strong>${money(data.vatTotal)}</strong></div>
          <div class="totalRow grand"><span>Total</span><strong>${money(data.total)}</strong></div>
          ${data.paymentMethod ? `<div class="totalRow"><span>Payment</span><strong>${escapeHtml(data.paymentMethod)}</strong></div>` : ''}
        </div>

        <div class="footer">
          Generated by Mobile POS. This document is stored locally on the device.
        </div>
      </body>
    </html>
  `;

  const result = await Print.printToFileAsync({
    html,
    base64: true,
  });

  if (!result.base64) {
    throw new Error(
      result.uri
        ? 'PDF was generated but Android did not return readable PDF data.'
        : 'PDF generation did not return any PDF data.'
    );
  }

  const safeName = data.number.replace(/[^a-zA-Z0-9_-]/g, '_');
  const targetUri = `${FileSystem.documentDirectory}${safeName}.pdf`;

  await FileSystem.writeAsStringAsync(targetUri, result.base64, {
    encoding: FileSystem.EncodingType.Base64,
  });

  const savedInfo = await FileSystem.getInfoAsync(targetUri);
  if (!savedInfo.exists) {
    throw new Error('PDF was generated but could not be saved to local storage.');
  }

  return targetUri;
}

export async function shareDocumentPdf(uri: string) {
  const available = await Sharing.isAvailableAsync();
  if (!available) throw new Error('Sharing is not available on this device.');

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Share PDF',
    UTI: 'com.adobe.pdf',
  });
}


type AnalyticsPdfData = {
  storeName?: string;
  storeCode?: string;
  date: string;
  summary: { invoiceCount: number; revenue: number; vat: number; paid: number };
  salesTrend: Array<{ day: string; invoices: number; revenue: number }>;
  popularItems: Array<{ ItemDesc: string; units: number; sales: number }>;
  topRevenue: Array<{ ItemDesc: string; units: number; sales: number }>;
  paymentMethods: Array<{ method: string; count: number; amount: number }>;
  customerSales: Array<{ customer: string; invoices: number; sales: number }>;
  lowStock: Array<{ ItemDesc: string; qty: number }>;
};

export async function generateAnalyticsPdf(data: AnalyticsPdfData): Promise<string> {
  const money = (value: number) => `R ${Number(value || 0).toFixed(2)}`;
  const esc = (value: any) => escapeHtml(String(value ?? ''));
  const rows = (items: any[], columns: (x: any, i: number) => string) =>
    items.map((x, i) => `<tr>${columns(x, i)}</tr>`).join('');

  const html = `
    <html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
      body { font-family: Arial, sans-serif; color:#111827; padding:30px; }
      h1 { margin:0 0 4px; font-size:24px; } h2 { margin:24px 0 8px; font-size:16px; }
      .muted { color:#6b7280; font-size:11px; } .summary { display:flex; flex-wrap:wrap; margin:18px 0; }
      .metric { background:#f3f4f6; padding:12px; margin:0 8px 8px 0; min-width:135px; }
      .metric strong { display:block; font-size:16px; margin-top:4px; }
      table { width:100%; border-collapse:collapse; margin-top:8px; }
      th { background:#111827; color:white; text-align:left; padding:8px; font-size:10px; }
      td { border-bottom:1px solid #e5e7eb; padding:7px; font-size:10px; }
      .right { text-align:right; } .footer { margin-top:30px; border-top:1px solid #e5e7eb; padding-top:10px; color:#6b7280; font-size:9px; }
    </style></head>
    <body>
      <h1>Sales Analytics Report</h1>
      <div class="muted">${esc(data.storeName || 'Mobile POS')} ${data.storeCode ? '• ' + esc(data.storeCode) : ''}</div>
      <div class="muted">Generated ${esc(data.date)}</div>

      <div class="summary">
        <div class="metric">Revenue<strong>${money(data.summary.revenue)}</strong></div>
        <div class="metric">Invoices<strong>${data.summary.invoiceCount}</strong></div>
        <div class="metric">VAT collected<strong>${money(data.summary.vat)}</strong></div>
        <div class="metric">Amount paid<strong>${money(data.summary.paid)}</strong></div>
      </div>

      <h2>Sales Trend</h2>
      <table><thead><tr><th>Date</th><th class="right">Invoices</th><th class="right">Revenue</th></tr></thead><tbody>
        ${rows(data.salesTrend, x => `<td>${esc(x.day)}</td><td class="right">${Number(x.invoices || 0)}</td><td class="right">${money(x.revenue)}</td>`)}
      </tbody></table>

      <h2>Popular Items</h2>
      <table><thead><tr><th>Item</th><th class="right">Units</th><th class="right">Sales</th></tr></thead><tbody>
        ${rows(data.popularItems, x => `<td>${esc(x.ItemDesc)}</td><td class="right">${Number(x.units || 0)}</td><td class="right">${money(x.sales)}</td>`)}
      </tbody></table>

      <h2>Top Revenue Items</h2>
      <table><thead><tr><th>Item</th><th class="right">Units</th><th class="right">Sales</th></tr></thead><tbody>
        ${rows(data.topRevenue, x => `<td>${esc(x.ItemDesc)}</td><td class="right">${Number(x.units || 0)}</td><td class="right">${money(x.sales)}</td>`)}
      </tbody></table>

      <h2>Payment Methods</h2>
      <table><thead><tr><th>Method</th><th class="right">Transactions</th><th class="right">Amount</th></tr></thead><tbody>
        ${rows(data.paymentMethods, x => `<td>${esc(x.method)}</td><td class="right">${Number(x.count || 0)}</td><td class="right">${money(x.amount)}</td>`)}
      </tbody></table>

      <h2>Top Customers</h2>
      <table><thead><tr><th>Customer</th><th class="right">Invoices</th><th class="right">Sales</th></tr></thead><tbody>
        ${rows(data.customerSales, x => `<td>${esc(x.customer)}</td><td class="right">${Number(x.invoices || 0)}</td><td class="right">${money(x.sales)}</td>`)}
      </tbody></table>

      <h2>Low Stock Alerts</h2>
      <table><thead><tr><th>Item</th><th class="right">Units Remaining</th></tr></thead><tbody>
        ${rows(data.lowStock, x => `<td>${esc(x.ItemDesc)}</td><td class="right">${Number(x.qty || 0)}</td>`)}
      </tbody></table>

      <div class="footer">Generated by Mobile POS. Analytics are based on locally stored invoice data.</div>
    </body></html>
  `;

  const result = await Print.printToFileAsync({ html, base64: true });
  if (!result.base64) throw new Error('Analytics PDF was generated but readable PDF data was not returned.');

  const targetUri = `${FileSystem.documentDirectory}analytics-report-${Date.now()}.pdf`;
  await FileSystem.writeAsStringAsync(targetUri, result.base64, {
    encoding: FileSystem.EncodingType.Base64,
  });

  const savedInfo = await FileSystem.getInfoAsync(targetUri);
  if (!savedInfo.exists) throw new Error('Analytics PDF could not be saved to local storage.');
  return targetUri;
}


type CustomerStatementPdfData = {
  customer: { AccCode: string; Company: string; Contact?: string; Tel?: string; Email?: string; CrLimit?: number };
  date: string;
  fromDate?: string;
  toDate?: string;
  transactions: Array<{ CreatedDt: string; TransactionType: string; RefNo?: string; Debit: number; Credit: number; Balance: number; Notes?: string }>;
  balance: number;
};

export async function generateCustomerStatementPdf(data: CustomerStatementPdfData): Promise<string> {
  const money = (value: number) => `R ${Number(value || 0).toFixed(2)}`;
  const esc = (value: any) => escapeHtml(String(value ?? ''));
  const rows = data.transactions.map(t => `
    <tr>
      <td>${esc(t.CreatedDt)}</td>
      <td>${esc(t.TransactionType)}</td>
      <td>${esc(t.RefNo || '')}</td>
      <td class="right">${t.Debit ? money(t.Debit) : '-'}</td>
      <td class="right">${t.Credit ? money(t.Credit) : '-'}</td>
      <td class="right">${money(t.Balance)}</td>
    </tr>
  `).join('');

  const period = data.fromDate || data.toDate
    ? `${esc(data.fromDate || 'Beginning')} to ${esc(data.toDate || 'Current')}`
    : 'All account activity';

  const html = `
    <html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
      body { font-family: Arial, sans-serif; color:#111827; padding:30px; }
      h1 { margin:0 0 5px; font-size:24px; } h2 { margin:22px 0 8px; font-size:16px; }
      .muted { color:#6b7280; font-size:11px; } .box { background:#f3f4f6; padding:14px; margin:18px 0; }
      table { width:100%; border-collapse:collapse; margin-top:10px; }
      th { background:#111827; color:white; padding:8px; font-size:10px; text-align:left; }
      td { border-bottom:1px solid #e5e7eb; padding:7px; font-size:10px; } .right{text-align:right;}
      .balance { font-size:18px; font-weight:bold; margin-top:12px; }
      .footer { margin-top:30px; border-top:1px solid #e5e7eb; padding-top:10px; color:#6b7280; font-size:9px; }
    </style></head><body>
      <h1>Customer Account Statement</h1>
      <div class="muted">${esc(data.customer.Company)} • ${esc(data.customer.AccCode)}</div>
      <div class="muted">Period: ${period}</div>
      <div class="muted">Generated: ${esc(data.date)}</div>
      <div class="box">
        <strong>Customer</strong><br/>${esc(data.customer.Company)}<br/>
        ${esc(data.customer.Contact || '')}<br/>${esc(data.customer.Tel || '')}<br/>${esc(data.customer.Email || '')}
        <div class="balance">Account Balance: ${money(data.balance)}</div>
        <div class="muted">Credit Limit: ${money(data.customer.CrLimit || 0)}</div>
      </div>
      <h2>Transactions</h2>
      <table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th class="right">Debit</th><th class="right">Credit</th><th class="right">Balance</th></tr></thead>
      <tbody>${rows}</tbody></table>
      <div class="footer">Generated by Mobile POS. This statement is stored locally on the device.</div>
    </body></html>
  `;

  const result = await Print.printToFileAsync({ html, base64: true });
  if (!result.base64) throw new Error('Statement PDF was generated but readable PDF data was not returned.');
  const safeName = data.customer.AccCode.replace(/[^a-zA-Z0-9_-]/g, '_');
  const targetUri = `${FileSystem.documentDirectory}statement-${safeName}-${Date.now()}.pdf`;
  await FileSystem.writeAsStringAsync(targetUri, result.base64, { encoding: FileSystem.EncodingType.Base64 });
  const savedInfo = await FileSystem.getInfoAsync(targetUri);
  if (!savedInfo.exists) throw new Error('Statement PDF could not be saved to local storage.');
  return targetUri;
}


export async function generateBusinessReportPdf(data: any, storeName: string, storeCode: string): Promise<string> {
  const money = (n:number) => `R ${Number(n||0).toFixed(2)}`;
  const esc = (v:any) => escapeHtml(String(v ?? ''));
  const productRows = (data.topProducts || []).map((x:any) => `<tr><td>${esc(x.ItemDesc)}</td><td>${Number(x.Qty).toFixed(2)}</td><td>${money(x.Sales)}</td><td>${money(x.Cost)}</td><td>${money(x.Profit)}</td></tr>`).join('');
  const paymentRows = (data.paymentMethods || []).map((x:any) => `<tr><td>${esc(x.method)}</td><td>${x.count}</td><td>${money(x.amount)}</td></tr>`).join('');
  const customerRows = (data.topCustomers || []).map((x:any) => `<tr><td>${esc(x.Company)}</td><td>${money(x.Sales)}</td><td>${money(x.Paid)}</td><td>${money(x.Outstanding)}</td></tr>`).join('');
  const html = `<html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"/><style>
  body{font-family:Arial;color:#111827;padding:28px}h1{font-size:24px;margin:0 0 4px}h2{font-size:16px;margin-top:22px}
  .muted{color:#6b7280;font-size:10px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.box{background:#f3f4f6;padding:12px;margin-top:12px}
  table{width:100%;border-collapse:collapse;margin-top:8px}th{background:#111827;color:white;padding:7px;text-align:left;font-size:9px}td{border-bottom:1px solid #e5e7eb;padding:6px;font-size:9px}
  </style></head><body>
  <h1>Business Performance Report</h1><div class="muted">${esc(storeName)} • ${esc(storeCode)}</div>
  <div class="muted">Period: ${esc(data.fromDate)} to ${esc(data.toDate)}</div>
  <div class="grid">
    <div class="box"><b>Revenue</b><br/>${money(data.sales.revenue)}</div>
    <div class="box"><b>Gross Profit</b><br/>${money(data.profit.grossProfit)}</div>
    <div class="box"><b>Margin</b><br/>${Number(data.profit.margin).toFixed(1)}%</div>
    <div class="box"><b>Invoices</b><br/>${data.sales.invoices}</div>
    <div class="box"><b>VAT</b><br/>${money(data.sales.vat)}</div>
    <div class="box"><b>Credit Sales</b><br/>${money(data.sales.creditSales)}</div>
  </div>
  <h2>Sales & Profit by Product</h2><table><tr><th>Product</th><th>Qty</th><th>Sales</th><th>Cost</th><th>Profit</th></tr>${productRows}</table>
  <h2>Payment Methods</h2><table><tr><th>Method</th><th>Count</th><th>Amount</th></tr>${paymentRows}</table>
  <h2>Top Customers</h2><table><tr><th>Customer</th><th>Sales</th><th>Paid</th><th>Outstanding</th></tr>${customerRows}</table>
  <h2>Inventory Snapshot</h2><div class="box">Stock value: ${money(data.stock.totalValue)}<br/>Low stock items: ${data.stock.lowStock}<br/>Out of stock: ${data.stock.outOfStock}</div>
  </body></html>`;
  const result = await Print.printToFileAsync({ html, base64: true });
  if (!result.base64) throw new Error('Report PDF data was not returned.');
  const targetUri = `${FileSystem.documentDirectory}business-report-${data.fromDate}-${data.toDate}-${Date.now()}.pdf`;
  await FileSystem.writeAsStringAsync(targetUri, result.base64, { encoding: FileSystem.EncodingType.Base64 });
  const info = await FileSystem.getInfoAsync(targetUri);
  if (!info.exists) throw new Error('Business report PDF could not be saved.');
  return targetUri;
}


export async function printDocumentPdf(uri: string) {
  if (!uri) throw new Error('PDF is not available for printing.');
  await Print.printAsync({ uri });
}
